### ISSUE TITLE
Dropping dependency on box 2d

### ISSUE THREAD

**Issue by msaroufim** [Bastacyclop/rust_box2d#11]
Seems to me like this is feasible and I'm happy to help

**Comment by Bastacyclop** [comment]
@msaroufim Hi!
What do you mean exactly by that? Do you want to drop the system library dependency by automatically building box2d from source, similar to what most `-sys` crates can do?

**Comment by msaroufim** [comment]
Hey @Bastacyclop no I actually mean turning this into a standalone Rust library with no dependency on Box 2D at all. I was gonna start doing this for Box 2D lite since it seems easier and was looking at your code for inspiration and was curious if you'd like to collaborate on something like this.

**Comment by Bastacyclop** [comment]
First of all, I am curious about your motivation for doing this work?

**Comment by msaroufim** [comment]
Yeah of course. I'd like to build an open source version of Mujoco. I think the robotics community would really benefit from having an OSS simulator, I also feel that Rust would make it easier to contribute and write more performant code with less bugs.

Before I go to 3D I expect that 2D is a logical first step. I would also like the engine differentiable which isn't something that physics engines generally are - see this http://diffsharp.github.io/DiffSharp/examples-inversekinematics.html

**Comment by Bastacyclop** [comment]
Interesting, I assume you looked at [nphysics](https://www.nphysics.org/) already?
I am afraid that I do not have much knowledge in implementing such engines, nor much free time these days.
I wish you all the best in this project and I am happy to discuss more if this can help you in any way :)

**Comment by msaroufim** [comment]
Yeah good point, I'll join their discord channel and see what they're up to.

Best of luck with your work too!
