### ISSUE TITLE
The lack of documentation is a real hinderance

### ISSUE THREAD

**Issue by corazza** [Bastacyclop/rust_box2d#12]
Hi, this code seems to have taken quite some effort, which is why I'm surprised that it's almost completely undocumented. By that I mean only source code is provided, even the official documentation is just source code with a search bar, no doc comments.

As a new user, this makes it extremely hard to use: things that could otherwise take a minute can take upwards of an hour (not to mention the possibility of something not even being supported).

I know this is supposed to be a thin wrapper around Box2D, however the difference is still large enough to cause confusion and necessitate documenting the edge cases.

Of course, for example, the step function or the idea of fixtures don't have to be documented. But how UserDataTypes are used and hundreds of other such things induced by the language difference totally require explanation.

**Comment by Bastacyclop** [comment]
Hi,
Thanks for the feedback, I am happy to add documentation where users would find it useful (I also welcome contributions).
Do you have specific features, other than user data, that you wish were explained?

**Comment by Bastacyclop** [comment]
@corazza I will add documentation for the user data soonish, let me know if you have other things in mind.

**Comment by Bastacyclop** [comment]
The master documentation upload seems to be broken, but I added some documentation for user data:
https://github.com/Bastacyclop/rust_box2d/compare/7b504a426f6e8f67ca5c17137102e0e524f20664..ebdc4da1197b9f5c9dd80afaa0cdc03b974c2cf6

**Comment by corazza** [comment]
Thank you for this response, and for your time! And sorry for not getting back to you, I'm on a pause from this project until the semester is over, and rarely check my GH notifications.

Anyways, I wish I'd documented my own path through using this crate, but as it turns out I don't remember the exact stuff that I wished was better documented. I'll try to backtrace a bit through my project to maybe come up with examples, but in a month or so when I'll have time.

What would be _most_ useful, however, are examples for frequently-used functions, and some overall examples on how to achieve simple tasks that a user might want. Maybe when I catch some time, I'll do a writeup on my blog, and examples of this kind could be extracted from there.

I'll try to be more helpful and provide examples later, as I said.

**Comment by Bastacyclop** [comment]
I'll close for now since there are no concrete plans on the way.
