### ISSUE TITLE
Docs for UserData

### ISSUE THREAD

**Issue by floriandotorg** [Bastacyclop/rust_box2d#2]
Hi,

thanks for this awsome bindings.

Is there any documentation on how to user UserData?

Thanks

**Comment by Bastacyclop** [comment]
Well, basically you provide a unit struct to specify the [user data types](https://bastacyclop.github.io/rust_box2d/wrapped2d/user_data/trait.UserDataTypes.html) that will be used for bodies, joints and fixtures. For example:

``` rust
use wrapped2d::b2;
use wrapped2d::user_data::*;
use my::ObjectId;

pub struct UserData;
impl UserDataTypes for UserData {
    type BodyData = Option<ObjectId>;
    type JointData = ();
    type FixtureData = FixtureKind;
}

pub type World = b2::World<UserData>;

pub enum FixtureKind {
    Wood,
    Metal,
}

// [ ... elsewhere ... ]

// small use cases
let h = world.create_body(&def); // not specifying user data will use `Default` (`None` here)
let h = world.create_body_with(&def, Some(object_id)); // specifying user data for the body
let user_data = world.body(h).user_data(); // access the body user data
```

Would you like to have such an example in the docs ?

**Comment by floriandotorg** [comment]
Hi @Bastacyclop,

thanks for the quick reply, this was extremely helpful.

Yes, something like this in the docs would be amazing.

Are there any docs beside the examples?

**Comment by Bastacyclop** [comment]
There is the actual rust-generated [documentation](https://bastacyclop.github.io/rust_box2d/wrapped2d/) that you have probably seen already. It is pretty raw but useful combined with the box2d [manual](http://box2d.org/manual.pdf).

PS: I don't have much time these days, but I'm open to issues, questions and PRs :)

**Comment by floriandotorg** [comment]
I didn't see the docs, I build everything upon the examples and the manual. If I find the time I'll prepare a MR to link the docs in the Readme.

Thanks a lot for your help :-)

**Comment by Bastacyclop** [comment]
The documentation link is already in the README (and on crates.io) though: click on the "Documentation" title.

**Comment by floriandotorg** [comment]
Totally overlooked it, thanks.

**Comment by Bastacyclop** [comment]
@floriandotorg So I guess you don't find having an user data example necessary anymore ?
I'm glad I could help you and was pleased to get some feedback ;)

**Comment by norru** [comment]
Hi @floriandotorg, I'm using @bastacyclop's excellent box2d wrapper with custom user data here, if it helps: https://github.com/itadinanta/rust-oids/blob/tags/0.3.0/src/backend/systems/physics.rs

**Comment by Peterculazh** [comment]
Hello, I'm totally copy-pasted your code and getting the error: `no method named "user_data" found for struct "std::cell::Ref<'_, wrapped2d::b2::MetaBody<UserData>>" in the current scope`.

There's my code:
```
extern crate piston_window;
extern crate testbed;
extern crate wrapped2d;

use wrapped2d::b2;
use wrapped2d::user_data::*;

pub type ObjectId = u64;

pub struct UserData;
impl UserDataTypes for UserData {
    type BodyData = Option<ObjectId>;
    type JointData = ();
    type FixtureData = FixtureKind;
}
pub type World = b2::World<UserData>;
pub enum FixtureKind {
    Wood,
    Metal,
}

fn main() {
    let mut world = World::new(&b2::Vec2 { x: 0., y: -10. });

    let player_def = b2::BodyDef {
        body_type: b2::BodyType::Dynamic,
        position: b2::Vec2 { x: 0., y: -15. },
        ..b2::BodyDef::new()
    };

    let h = world.create_body_with(&player_def, Some(2)); // specifying user data for the body

    let user_data = world.body(h).user_data(); // access the body user data // There goes error
}
```

I'm new to Rust, but code looks like we shadowing the `UserData` with passing new struct with same name and we have to implement again `user_data()` method for `UserData` structure. Or I'm doing something incorrect?

**Comment by Bastacyclop** [comment]
Hi @Peterculazh, I think you are right, try using a different name like `CustomUserData` and it should work. I [updated the documentation](https://github.com/Bastacyclop/rust_box2d/commit/a784aa58140326715ece22e8c7c15f0ab348264b). Thanks for spotting this.
