### ISSUE TITLE
Where are the Box2D files expected to be? What files are expected?

### ISSUE THREAD

**Issue by samhh** [Bastacyclop/rust_box2d#8]
As someone with no C++ experience this has been rather confusing... what exactly is expected of the Box2D dependency regards its location and its contents? I've tried pointing to it locally w/ `BOX2D_INCLUDE_PATH` as well as putting what I think are the correct Box2D contents in `/usr/local/include/` to no avail. Help appreciated :-)

macOS, Rust 1.21.0

**Comment by Bastacyclop** [comment]
@SamHH Hi, sorry about the confusion. Both the dynamic Box2D library and the Box2D header files are expected to be accessible. The dynamic library is needed at runtime to call Box2D functions while the header files are describing the Box2D API and are needed for compilation. I don't know how it works on macOS exactly but on Linux the easiest way is to simply install Box2D on your system with your package manager or [directly from source](https://github.com/Bastacyclop/rust_box2d/blob/master/.travis.yml). 

Hope this helps, don't hesitate if you need more information :)

**Comment by samhh** [comment]
Unlike all the others I'd found, those build steps actually worked perfectly... thank you!
